autocompleter for keywords and types
OpenModelica/OMEdit pull request #117
Opened 2017-04-05 12:40 UTC by arun3688

2017-04-06 09:10 UTC, adeas31 requested changes

2017-04-06 09:10 UTC, adeas31 commented on OMEdit/OMEditGUI/Editors/BaseEditor.cpp
> +  : QPlainTextEdit(pBaseEditor),mpcompleter(0),mpBaseEditor(pBaseEditor)
Use CamelCase for variable names.

2017-04-06 09:10 UTC, adeas31 commented on OMEdit/OMEditGUI/Editors/BaseEditor.cpp
> +  mpStandardItem = new QStandardItem();
Why in this world we need `mpStandardItem`?

2017-04-06 09:10 UTC, adeas31 commented on OMEdit/OMEditGUI/Editors/BaseEditor.cpp
> +  if (mpcompleter->widget() != this)
This is just a non necessary check since we always know that it is false.

2017-04-06 09:10 UTC, adeas31 commented on OMEdit/OMEditGUI/Editors/BaseEditor.cpp
> +}
This function seems fishy.....Looks like the text remained selected after this function call.
Shouldn't we clear the selection after reading the text?

2017-04-06 09:10 UTC, adeas31 commented on OMEdit/OMEditGUI/Editors/MetaModelicaEditor.cpp
> +  mpMetaModelicaHighlighter = new MetaModelicaHighlighter (OptionsDialog::instance()->getMetaModelicaEditorPage(),this->getPlainTextEdit());
Why are you creating a new highlighter here?
We already have the highlighter in `ModelWidget` class.

2017-04-06 09:10 UTC, adeas31 commented on OMEdit/OMEditGUI/Editors/MetaModelicaEditor.cpp
> +    QString newpattern = QString("\\b%1\\b").arg(pattern);
CamelCase please.

2017-04-06 09:10 UTC, adeas31 commented on OMEdit/OMEditGUI/resource_omedit.qrc
> +        <file>Resources/icons/keyword.png</file>
Don't add png images. Use svg.

2017-04-06 16:06 UTC, arun3688 commented
updated the code with changes suggested

2017-04-06 17:20 UTC, adeas31 commented on OMEdit/OMEditGUI/Editors/BaseEditor.cpp
> +    mpStandardItem =new QStandardItem(keywords[i]);
You could do,
`QStandardItem *pStandardItem = new QStandardItem(keywords[i]);`
and get rid of `mpStandardItem`.

2017-04-06 17:22 UTC, adeas31 commented on OMEdit/OMEditGUI/Editors/MetaModelicaEditor.h
> +class MetaModelicaHighlighter;
Forward declaration is not required now.

2017-04-06 17:23 UTC, adeas31 commented on OMEdit/OMEditGUI/Editors/TransformationsEditor.cpp
> +QStringList TransformationsEditor::getKeywords()
Why does `TransformationsEditor` still have `getKeywords()` and `getTypes()` functions?

2017-04-06 17:25 UTC, adeas31 commented
I believe now we can have keywords & types auto complete for all editor types. So could you please add it. Also please add the source code documentation to your code.

2017-04-06 17:40 UTC, adeas31 commented
The svg icons looks horible. Seems like you converted your png images to svg using some online converter. Can you create new better 32*32 size svg icons?

2017-04-06 17:41 UTC, adeas31 commented
Once you have the list of keywords and types then sort them alphabetically.
Better to use natural sort.

2017-04-07 13:10 UTC, arun3688 commented
fixed the comments suggestion

2017-04-07 14:20 UTC, arun3688 commented
The sorting is done with the help of QsortfilterProxy model which exactly does the natural sorting

2017-04-07 14:46 UTC, hkiel requested changes

2017-04-07 14:46 UTC, hkiel commented on OMEdit/OMEditGUI/Editors/ModelicaEditor.cpp
> +  return keywordsList;
At least "pre", "size" and "noEvent" are missing.
Have a look at http://modref.xogeny.com/

2017-04-07 19:05 UTC, arun3688 commented on OMEdit/OMEditGUI/Editors/ModelicaEditor.cpp
> +  return keywordsList;
according to the book written by peter fritzson and also from the modelica specification they are not coming under keywords.  https://www.modelica.org/documents/ModelicaSpec30.pdf (Page no.12)

2017-04-07 21:13 UTC, hkiel approved these changes

2017-04-10 08:18 UTC, adeas31 approved these changes

2017-04-10 08:18 UTC, merged