add search history,expandcollapse to search operation
OpenModelica/OMEdit pull request #160
Opened 2018-02-27 17:00 UTC by arun3688

2018-02-28 13:23 UTC, adeas31 requested changes
Just few minor fixes required.

2018-02-28 13:23 UTC, adeas31 commented on OMEdit/OMEditGUI/Search/SearchWidget.cpp
> +  QString searchHistoryItem = QString("%1%2%3 %4").arg("Project-").arg(mpSearchScopeComboBox->currentText()).arg(":").arg(mpSearchStringComboBox->currentText());
Why not,
`QString("%1-%2: %3").arg(tr("Project")).arg(mpSearchScopeComboBox->currentText()).arg(mpSearchStringComboBox->currentText());`

2018-02-28 13:23 UTC, adeas31 commented on OMEdit/OMEditGUI/Search/SearchWidget.h
> +  QList<SearchWidgetResult*> pSearchWidgetResultobjects;
This is a list not a pointer. So it should be `QList<SearchWidgetResult*> mSearchWidgetResultobjects;`

2018-02-28 13:23 UTC, adeas31 commented on OMEdit/OMEditGUI/Search/SearchWidget.h
> +class SearchWidgetResult : public QWidget
A proper name would be **SearchResultWidget**.

2018-02-28 14:23 UTC, arun3688 commented
@adeas31 , fixed the changes

2018-02-28 19:33 UTC, adeas31 commented
* I still see the text **Searching 1093 of 1093 files. Please wait for a while** after the search is finished.
* Unable to cancel the search.
* Pressing `ctrl+h` doesn't show the Search Browser when I tab it in the dock widget.

2018-03-01 09:16 UTC, arun3688 commented
Unable to cancel the search.?, Are you not able to cancel the search in which scenario.
I am able to cancel the search,

2018-03-01 11:18 UTC, arun3688 commented
updated the changes

2018-03-01 12:18 UTC, adeas31 approved these changes

2018-03-01 12:18 UTC, merged