Basic implementation of completion for Modelica code
OpenModelica/OMEdit pull request #171
Opened 2018-07-28 16:33 UTC by atrosinenko

Complete everything against the latest successfully saved version of the top-level class opened in the current editor.

Partially fixes [this ticket](https://trac.openmodelica.org/OpenModelica/ticket/3847).

This should already be better than nothing. On the other hand, here are things that probably should be done as well. Should they go to this single PR?

- [X] Basic implementation
- [ ] Optimization (cache static items somewhere -- has it any performance implications at all?)
- [ ] Add an icon for new completion type
- [ ] Add **different** icons for different symbol types (how many?)
- [ ] Respect **class** under cursor (consider nested classes in single file)

2018-07-28 16:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenModelica/OMEdit?pullRequest=171) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenModelica/OMEdit?pullRequest=171) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenModelica/OMEdit?pullRequest=171) it.</sub>

2018-08-04 10:55 UTC, atrosinenko commented
Added an icon made of existing completerType.svg. Hope it isn't against CLA.

2018-08-06 11:52 UTC, adeas31 commented
Performance has the high priority here. I believe we should stay inside Qt data structures as much as possible and should avoid calls to OMC. All the calls you are doing to OMC are already done and should be avoided. For example, right now if you create a new model and then switch to text view and just press ctrl+space, as a result of this action you are sending 10 commands to OMC whose response time depends very much on the model. I suggest the following,

* Fetch the information of loaded classes from the Libraries Browser.
* Fetch the information of the inherited classes and components from the `ModelWidget` class.

2018-08-06 16:57 UTC, atrosinenko commented
Now it should not call backend without necessity. But now code review is even more required.

2018-08-08 08:05 UTC, atrosinenko commented
Quick fix: collect completion from outer packages. Now there is a false positive `All`, but completion anyways is not precise now...

2018-08-20 16:35 UTC, atrosinenko commented
Autocompletion is a very broad topic, so what is expected from me to be done in this PR and what can be left as is / for the next PRs?

2018-08-20 17:41 UTC, adeas31 commented
Unfortunately, I am busy with other things and don't have enough time to review your changes. I don't promise anything but will try to review this or next week.

2018-08-21 10:22 UTC, atrosinenko commented
I just asked in case there is something implicitly expected from me that I don't realize. If you are busy then please excuse me for disturbance, my previous post was not about "review this ASAP". :)

2018-10-02 11:23 UTC, atrosinenko commented
Is there any updates on this PR? Is it postponed till 1.13 release?

2018-10-04 09:45 UTC, adeas31 commented
Yes. I think we should not push this in until the release.

2018-10-04 09:46 UTC, atrosinenko commented
OK. Thank you.

2019-01-05 08:54 UTC, atrosinenko commented
Ping :)

2019-01-14 14:41 UTC, adeas31 requested changes
LGTM. What are the plans for the remaining items in the PR?

> Add different icons for different symbol types (how many?)

I think we should just consider classes and components. So 2 icons one for classes and one for components should be enough. If easier maybe we can differentiate between inherited classes. However, I believe the icon is not so important. I think we should improve the details of the tooltip. In the tooltip we should show more information about the selected completer item.

There are few minor things that I have noticed while testing,

- The first popup item should be selected so I can use it by pressing enter. Right now I have to press down arrow and then enter.
- We should show the popup after the `.` is pressed. For example, user types Modelica and then `.` after that show the popup. Right now I have to press ctrl+space.

2019-01-14 14:41 UTC, adeas31 commented on OMEdit/OMEditGUI/Modeling/LibraryTreeWidget.cpp
> +      if (classes[i]->getName().startsWith(lastPart))
Yes `All` is a special `LibraryTreeItem` that is used for search functionality but is hidden and not shown to the user. You need to filter it here.

`if (classes[i]->getName().startsWith(lastPart) && classes[i]->getNameStructure().compare("OMEdit.Search.Feature") != 0)`

2019-01-14 14:41 UTC, adeas31 commented on OMEdit/OMEditGUI/Modeling/LibraryTreeWidget.cpp
> +    }
The root `LibraryTreeItem` is just a container. It is not a valid Modelica class so asking for its components will lead to an error. You need to check for it here,

```
if (!baseClasses[bc]->isRootItem()) {
      const QList<ComponentInfo*> &components = baseClasses[bc]->getComponentsList();
      for (int i = 0; i < components.size(); ++i) {
        if (components[i]->getName().startsWith(lastPart))
          result.insert(components[i]->getName());
      }
    }
```

Note that OMEdit can also load non-Modelica items like OMSimulator models, composite models. text files etc. So you need to check for it as well i.e., add the following to the above if condition `baseClasses[bc]->getComponentType() == LibraryTreeItem::Modelica`

2019-01-14 14:52 UTC, atrosinenko commented
Remaining items are more for reviewers: these are some ideas on what should be done right now and what can be postponed to subsequent PRs. Personally I think it is worth to have some "beta that is better than nothing" version of completion right now and improve it later instead of trying to bring in some ideal completion functionality in one merge (that is, postpone remaining issues to future PRs).

Thank you for your review comments, I hope I will fix them soon.

2019-01-14 17:13 UTC, atrosinenko commented
Amended my PR as suggested and hopefully fixed one of "minor things" (popping up of completion on `.`). I have not managed to implement selection of the first completion item, though.

2019-01-15 12:28 UTC, casella commented
@AndreaBartolini, you may be interested in watching this progress

2019-01-15 14:21 UTC, adeas31 commented
> Amended my PR as suggested and hopefully fixed one of "minor things" (popping up of completion on `.`).

Thanks for the fixes.

> I have not managed to implement selection of the first completion item, though.

Just wondering if you are still working on it or should we merge this PR then?

2019-01-15 14:49 UTC, atrosinenko commented
Ultimately, the first item becomes auto-selected... I still cannot understand why current item sometimes becomes de-synchronized with the visually selected one. But even if it is regression of this PR (I cannot quickly prove / disprove it because of quite restricted hardcoded completion item set in the master branch), this looks not too significant comparing to the possibility to at least see (and select with partial visual feedback, in fact) the next word to enter.

> Just wondering if you are still working on it or should we merge this PR then?

I would prefer to merge at least something, and then improve later.

2019-01-16 14:40 UTC, adeas31 commented
Tested a bit more and it seems to work well.
Can you squash the commits? Makes it easier if we want to port it to 1.13 release.

2019-01-16 14:50 UTC, atrosinenko commented
I can squash the commits 2-3 hours later. Maybe GitHub can squash the commits automatically if properly ask it?

2019-01-16 14:52 UTC, adeas31 commented
We have that option disabled for the PRs. We had have issues with it in the past. It works better with the manual squash and then rebase and merge of PR.

2019-01-16 14:57 UTC, atrosinenko commented
OK, no problem at all. I hope to merge it about 2 hours later.

2019-01-16 16:18 UTC, atrosinenko commented
Pushed the result of `git rebase -i master` with squashing.

2019-01-16 19:19 UTC, merged

2019-01-22 23:47 UTC, casella commented
@atrosinenko, thanks a lot for your contribution, I just tried it and it's really nice.

Can you please register on trac.openmodelica.org, so I can assign ticket [#3847](https://trac.openmodelica.org/OpenModelica/ticket/3847) to you?

I think the most important missing feature now is to take care of inheritance. For example, if you type Modelica.Media.Interfaces.PartialTwoPhaseMedium. (which is something I do often, BTW), only the classes defined or re-declared there show up. In fact, there are many others defined or re-defined in the ancestor classes Modelica.Media.Interfaces.PartialPureSubstance and Modelica.Media.Interfaces.PartialMedium. 

If the drop-down list showed up also the classes defined or re-declared within all the ancestor classes, it would be a real bonus, because it's quite hard, particularly for beginner users of Modelica.Media, to figure out what is defined and where.

If you need to fetch this information from the API, you can ask @adrpo and @perost how to do it.

Thanks!

2019-01-23 07:22 UTC, atrosinenko commented
Thanks @adeas31 for review comments!

> Can you please register on trac.openmodelica.org, so I can assign ticket #3847 to you?

Looks like users are manually registered by @adrpo according to [this page](https://openmodelica.org/developersresources/source-code).

2019-01-23 07:30 UTC, adrpo commented
@atrosinenko: Yes. I will make you a user in Trac with the same username as here.

2019-01-23 07:58 UTC, adrpo commented
@atrosinenko: user created, check your email.

2019-01-23 08:16 UTC, atrosinenko commented
@adrpo: Received, thanks!