Autocompletion improvements
OpenModelica/OMEdit pull request #210
Opened 2019-01-27 17:29 UTC by atrosinenko

For review: new version allows for injection of HTML into comments (as well as other strings to be output). Should it be considered as a feature, a bug, or a security issue?

2019-01-28 06:29 UTC, atrosinenko commented
Added handling of non-malicious text that breaks HTML output.

2019-01-30 10:41 UTC, adeas31 requested changes
> For review: new version allows for injection of HTML into comments (as well as other strings to be output). Should it be considered as a feature, a bug, or a security issue?

The Modelica specification allows it so I consider it a feature.

I am unable to compile your code. It says,

```
Editors\BaseEditor.cpp: In constructor 'CompleterItem::CompleterItem(const QString&, const QString&, const QString&)':
Editors\BaseEditor.cpp:765:42: error: no matching function for call to 'QString::arg(QStringRef)'
         .arg(QStringRef(&value).left(ind))
```

Maybe because of different Qt versions.

2019-01-30 17:50 UTC, atrosinenko commented
Slightly rewritten the PR: added explicit `QStringRef::toString()` (hope it presents in any version of Qt), replaced sequences of `.arg(str)` with multi-argument `.arg(str1, str2, str3)` (supposing it works faster) and adjusted escaping heuristics a bit, so it would pass through correct tags (and some incorrect...).

2019-02-04 08:04 UTC, adeas31 approved these changes

2019-02-04 08:04 UTC, merged